import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '../../app/globals.css'
import Providers from "@/components/Providers";
import { SidebarTrigger } from "@/components/ui/sidebar";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "JB Audio Novelas",
  description: "Generated by create next app",
  other:{
     'google-adsense-account': 'ca-pub-5408528891828007',
  }
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex w-full`}
      >
        <Providers>
          <Navbar />
          <SidebarTrigger />
          {children}
        </Providers>
    
    </div>
  );
}
